version: 1
builder:
  configs:
    - platform: macos-spm
      swift_version: '5.9'
      scheme: public-api-diff
      documentation_targets: [
        PADProjectBuilder,
        PADPackageFileAnalyzer,
        PADSwiftInterfaceDiff,
        PADOutputGenerator,
        PADSwiftInterfaceFileLocator,
        PADCore,
        PADLogging
      ]
