version: 1
builder:
  configs:
    - platform: macos
      documentation_targets: [
        PADProjectBuilder,
        PADPackageFileAnalyzer,
        PADSwiftInterfaceDiff,
        PADOutputGenerator
      ]
