name: 'Swift Public API Diff'
description: 'Diff 2 versions of your Swift SDK'
inputs:
    platform:
        description: 'The platform to build the project for (iOS/macOS)'
        required: true
    new:
        description: 'Specify the updated version to compare to'
        required: true
    old:
        description: 'Specify the old version to compare to'
        required: true
runs:
    using: 'composite'
    steps:
    - name: "Run Diff"
      run: |
        NEW=${{ inputs.new }}
        OLD=${{ inputs.old }}
        PLATFORM=${{ inputs.platform }}
        PROJECT_FOLDER=$PWD
        echo $PROJECT_FOLDER
        
        swift run public-api-diff project --new "$NEW" --old "$OLD" --platform "$PLATFORM" --output "$PROJECT_FOLDER/api_comparison.md" --log-output "$PROJECT_FOLDER/logs.txt"
        cat "$PROJECT_FOLDER/logs.txt"
        
        cat "$PROJECT_FOLDER/api_comparison.md" >> $GITHUB_STEP_SUMMARY
      shell: bash
      
    - if: ${{ github.event.pull_request.base.ref != '' }}
      name: 📝 Comment on PR
      uses: thollander/actions-comment-pull-request@v3
      with:
        file-path: "${{ github.workspace }}/api_comparison.md"
        comment-tag: api_changes
        mode: recreate
        


