name: 'Swift Public API Diff'
description: 'This tool allows comparing 2 versions of a swift (sdk) project and lists all changes in a human readable way. And outputs it to the step summary or PR comment.'
inputs:
    platform:
        description: 'The platform to build the project for (iOS/macOS)'
        required: true
    new:
        description: 'Specify the updated version to compare to'
        required: true
    old:
        description: 'Specify the old version to compare to'
        required: true
runs:
    using: 'composite'
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "Adyen/adyen-swift-public-api-diff"
        #ref: "0.7.0"
    - name: Cache Swift Build
      uses: actions/cache@v3
      with:
        path: |
            $(swift build --configuration release --show-bin-path)
        key: ${{ runner.os }}-swift-build-6ec5ba25648323a388a756636e7f668b04d9f615
        #key: ${{ runner.os }}-swift-build-${{ github.sha }}
    - name: "Run Diff"
      run: |
        NEW=${{ inputs.new }}
        OLD=${{ inputs.old }}
        PLATFORM=${{ inputs.platform }}
        PROJECT_FOLDER=$PWD
        echo $PROJECT_FOLDER
        
        # Build the Swift project in release configuration and get the binary path 
        BINARY_DIR_PATH=$(swift build --configuration release --show-bin-path) 
        BINARY_PATH="$BINARY_DIR_PATH/public-api-diff"
        
        # Check if the binary exists 
        if [ ! -f "$BINARY_PATH" ]; then 
            
            echo "📭 Binary not found at $BINARY_PATH. Building the project..." 
            swift build --configuration release
            
            # Check if the build was successful 
            if [ ! -f "$BINARY_PATH" ]; then 
                echo "Build failed"
                exit 1
            fi
        else 
            echo "📬 Binary found at $BINARY_PATH" 
        fi 
        
        echo "▶️ Running binary at $BINARY_PATH" 
        $BINARY_PATH project --new "$NEW" --old "$OLD" --platform "$PLATFORM" --output "$PROJECT_FOLDER/api_comparison.md" --log-output "$PROJECT_FOLDER/logs.txt"
        cat "$PROJECT_FOLDER/logs.txt"
        
        cat "$PROJECT_FOLDER/api_comparison.md" >> $GITHUB_STEP_SUMMARY
      shell: bash
      
    - if: ${{ github.event.pull_request.base.ref != '' }}
      name: 📝 Comment on PR
      uses: thollander/actions-comment-pull-request@v3
      with:
        file-path: "${{ github.workspace }}/api_comparison.md"
        comment-tag: api_changes
        mode: recreate
        


