name: 🧹 Cancel duplicate work flows
permissions:
  actions: write
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  cancel-multiple-workflow-runs:
    name: "Cancel the self CI workflow run"
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel 'detect-api-changes'"
        uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: detect-api.changes.yml
      - name: "Cancel 'build-release'"
        uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-release.yml
      - name: "Cancel 'run-tests'"
        uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: run-tests.yml
