name: 🧪 Test composite action

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'action.yml'
  workflow_dispatch:
    inputs:
      new:
        description: 'Branch/tag of the new/updated version'
        required: true
      old:
        description: 'Branch/tag of the old/comparison version'
        required: true

permissions:
  contents: read
  actions: write
  pull-requests: write

jobs:
  test-action:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: n1hility/cancel-previous-runs@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.2.0'

    - name: 👾 Define Diff Versions
      shell: bash
      run: |
        NEW_VAL="${SOURCE}~${HEAD_REPO}"
        OLD_VAL="${TARGET}~${BASE_REPO}"

        if [[ "$TARGET_BRANCH" == release/* ]]; then
            LATEST_TAG=$(git describe --tags --abbrev=0)
            OLD_VAL="$LATEST_TAG~${BASE_REPO}"
        fi

        echo "OLD_VERSION=$OLD_VAL" >> "$GITHUB_ENV"
        echo "NEW_VERSION=$NEW_VAL" >> "$GITHUB_ENV"
      env:
        SOURCE: ${{ github.event.inputs.new || github.head_ref }}
        TARGET: ${{ github.event.inputs.old || github.event.pull_request.base.ref }}
        HEAD_REPO: ${{ github.server_url }}/${{ github.event.pull_request.head.repo.full_name || github.repository }}.git
        BASE_REPO: ${{ github.server_url }}/${{ github.repository }}.git
        TARGET_BRANCH: ${{ github.head_ref || 'no target branch' }}

    - name: 🔍 Run API diff (via composite action)
      uses: ./
      with:
        platform: macOS
        new: ${{ env.NEW_VERSION }}
        old: ${{ env.OLD_VERSION }}
        comment_tag: action_test_macOS
